### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by bhadresh74** [hellochick/PSPNet-tensorflow#1]
@hellochick 
Thank you for making your scripts public for the reference.
I was wondering if these tensorflow version of PSPNet accommodates the training data with different size?
My training data is [360X480X3] image and testing data is [360X480] grayscale image with class labelled as [0..N].
Again, appreciation for your contribution.

Bhadresh

**Comment by hellochick** [comment]
@bhadresh74, Yes, you can use your dataset on it, because it will still pad your image to [713x713].
And the reason why resolution is [713x713], since the average_pooling kernel size is fix in pyramid module, it can only process data size > 713x713.  I'll try to fix this problem.

**Comment by bhadresh74** [comment]
@hellochick Cool. I will give it a try.
Thanks

**Comment by gengqichuan** [comment]
@hellochick
Excuse me. Because only the TF 1.1 can run on our platform, I am wondering if this version can be used?
Thank you for your help!
Again, appreciation for your contribution
Geng Qichuan
