### ISSUE TITLE
version of tf and the gather layer

### ISSUE THREAD

**Issue by gengqichuan** [hellochick/PSPNet-tensorflow#2]
@hellochick
Excuse me. Because only the TF 1.1 can run on our platform, I am wondering if this version can be used?
Thank you for your help!
Again, appreciation for your contribution
Geng Qichuan

**Comment by hellochick** [comment]
Hey, @gengqichuan , I use tensorflow 1.3. I will try to implement tf 1.1 version !

**Comment by gengqichuan** [comment]
OK！thank you very much！And then，how do you deal with the gather layer in original pspnet？

**Comment by hellochick** [comment]
@gengqichuan , Hey, I have tried tf version 1.1, it can work without any modification. You can run on your platform directly, but It seems to be much slower than running on tf 1.3. For gather layer, I use `tf.images.resize_bilinear` for interp layer, you can take a look at `model.py`
