### ISSUE TITLE
Difference in Color Mapping to Label Id

### ISSUE THREAD

**Issue by MichaelX99** [hellochick/PSPNet-tensorflow#30]
Hello,

I was just curious about why the color to label id mapping for your code was different than the Cityscapes mapping found at https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py

Thank you for posting this though, your code is very well written and has been a huge help!

**Comment by hellochick** [comment]
Hey,

I think the problem is that I have already convert the label image through this [script] (https://github.com/mcordts/cityscapesScripts). I converted the original label in to TrainIdLabelImgs.

Thank you!

**Comment by MichaelX99** [comment]
Thank you!
