### ISSUE TITLE
Getting segmentation mask and class name predictions for ADE20k inference

### ISSUE THREAD

**Issue by jin-zhe** [hellochick/PSPNet-tensorflow#31]
Hi I'm running inference based on the model trained on ADE20K dataset and I would like to:
(1) Derive the segmentation mask. i.e. matrix with same rows x cols as image but each cell reflected the class id prediction for the pixel
(2) Get the corresponding ADE20K class name given a class id

**Comment by jin-zhe** [comment]
I found my answer here: https://github.com/CSAILVision/sceneparsing

**Comment by shadydiaa** [comment]
but this coded in maltab can you share the code in python to get mask and class name , Thanks 
@jin-zhe

**Comment by jin-zhe** [comment]
Hey @shadydiaa 

- To get mask, at *line 111* of `inference.py`, simply do `seg_map = sess.run(raw_output_up)`
- For class names, you just have to look at *objectInfo150* in the repo which comes in *.txt*, *.csv*, and *.mat* (any one will do). There's no need for matlab
