### ISSUE TITLE
InvalidArgumentError (see above for traceback): assertion failed: 

### ISSUE THREAD

**Issue by Leequens** [hellochick/PSPNet-tensorflow#44]
Thank you very much for your code.
When I run evaluate.py I get this erro：
 [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (mean_iou/confusion_matrix/control_dependency:0) = ] [3 3 3...] [y (mean_iou/ToInt64_1:0) = ] [19]

How can I solve it? Thanks.

**Comment by huyphongdo** [comment]
I have got the same issued can anyone can solve it ?

**Comment by zc12345** [comment]
> Thank you very much for your code.
> When I run evaluate.py I get this erro：
> [`labels` out of bound] [Condition x < y did not hold element-wise:] [x (mean_iou/confusion_matrix/control_dependency:0) = ] [3 3 3...] [y (mean_iou/ToInt64_1:0) = ] [19]
> 
> How can I solve it? Thanks.

I have got the same InvalidArgumentError, could you tell me how did you solve it ?
