### ISSUE TITLE
ignoring label 0 in ade20k doesn't give the same labeling as the check point results

### ISSUE THREAD

**Issue by AyaMohamedS** [hellochick/PSPNet-tensorflow#50]
i set index 0 to be ignored for ade20k training
but in testing my trained model, i got class label 0 and person's label becomes 13 not 12 as in the check point model
what can i do to fix this problem? and what is the expected labeling output for a model trained on the ade20k_2016challenge?

**Comment by AyaMohamedS** [comment]
i solved the problem by adjusting image reader (random_crop_and_pad_image_and_labels function) to convert label 0 into 255 before subtracting 1 from label tensor then convert 254 to 255 

and i kept ignore label =255 in  train.py

**Comment by tjqinwind** [comment]
can I have  a look at you code? i still have a litter confuse.
